---

- hosts: all
  become: true
  tasks:


# name, status and update_cache ar all options for  apt
  - name: install package
    apt:
      name: 
        - git
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

