---

- hosts: all
  become: true
  pre_tasks:

# name, status and update_cache ar all options for  apt
  - name: update repo cache
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution in ["Debian", "Ubuntu"]

- hosts: all
  become: true
  roles:
    - base

- hosts: desktop
  become: true
  roles:
    - desktop


