---

- hosts: all
  become: true
  pre_tasks:

# name, status and update_cache ar all options for  apt
  - name: install updates
    apt:
      upgrade: safe
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

# install packages
- hosts: desktop
  become: true
  tasks:

  - name: install package
    apt:
      name:
        - git
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]

